-- Generated by Oracle SQL Developer Data Modeler 19.1.0.081.0911
--   at:        2021-11-02 15:37:13 EDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

DROP TABLE address CASCADE CONSTRAINTS;
DROP TABLE customer CASCADE CONSTRAINTS;
DROP TABLE customer_address CASCADE CONSTRAINTS;
DROP TABLE customer_contract CASCADE CONSTRAINTS;
DROP TABLE daily_route CASCADE CONSTRAINTS;
DROP TABLE delivery CASCADE CONSTRAINTS;
DROP TABLE delivery_drivers CASCADE CONSTRAINTS;
DROP TABLE department CASCADE CONSTRAINTS;
DROP TABLE department_delivery_drivers CASCADE CONSTRAINTS;
DROP TABLE hours_ CASCADE CONSTRAINTS;
DROP TABLE invoice CASCADE CONSTRAINTS;
DROP TABLE package_ CASCADE CONSTRAINTS;
DROP TABLE person CASCADE CONSTRAINTS;
DROP TABLE receiver CASCADE CONSTRAINTS;
DROP TABLE relay_point CASCADE CONSTRAINTS;
DROP TABLE relay_point_contract CASCADE CONSTRAINTS;
DROP TABLE relay_rate CASCADE CONSTRAINTS;

CREATE TABLE customer (
    idcustomer      INTEGER NOT NULL PRIMARY KEY,
    compagny_name   VARCHAR2(20 CHAR),
    telephone       VARCHAR2(20 CHAR)
);

CREATE TABLE customer_contract (
    idcontract    INTEGER NOT NULL PRIMARY KEY,
    start_date    DATE,
    end_date      DATE NOT NULL,
    coef_weight   NUMBER,
    coef_size     NUMBER,
    active        CHAR(1),
    idcustomer    INTEGER NOT NULL,
    FOREIGN KEY (idcustomer) REFERENCES customer(idcustomer)
);

CREATE TABLE invoice (
    idinvoice       INTEGER NOT NULL PRIMARY KEY,
    paid            CHAR(1),
    emission_date   DATE,
    payment_date    DATE,
    price           NUMBER,
    nb_packages     INTEGER,
    delivery_r_r    INTEGER,
    delivery_r_a    INTEGER,
    delivery_a_r    INTEGER,
    delivery_a_a    INTEGER,
    idcustomer      INTEGER NOT NULL,
    FOREIGN KEY (idcustomer) REFERENCES customer(idcustomer)
);

CREATE TABLE package_ (
    idpackage   INTEGER NOT NULL PRIMARY KEY,
    size_      INTEGER,
    weight      INTEGER
);

CREATE TABLE department (
    number_    INTEGER NOT NULL,
    country    VARCHAR2(20 CHAR) NOT NULL,
    name_       VARCHAR2(20 CHAR),
    PRIMARY KEY (number_,country)
);

CREATE TABLE address (
    idaddress    INTEGER NOT NULL PRIMARY KEY,
    street       VARCHAR2(40 CHAR),
    number_      INTEGER,
    city         VARCHAR2(20 CHAR),
    postalcode   VARCHAR2(10 CHAR),
    number_department     INTEGER NOT NULL,
    country_department     VARCHAR2(20 CHAR) NOT NULL,
    FOREIGN KEY (number_department,country_department) REFERENCES department(number_,country)
);



CREATE TABLE customer_address (
    idcustomer INTEGER NOT NULL,
    idaddress INTEGER NOT NULL,
    PRIMARY KEY(idaddress,idcustomer),
    FOREIGN KEY (idcustomer) REFERENCES customer(idcustomer),
    FOREIGN KEY (idaddress) REFERENCES address(idaddress)
    
);

CREATE TABLE delivery_drivers (
    lastname    VARCHAR2(20 CHAR),
    firstname   VARCHAR2(20 CHAR),
    idperson    INTEGER NOT NULL PRIMARY KEY,
    idaddress   INTEGER NOT NULL,
    FOREIGN KEY (idaddress) REFERENCES address(idaddress)
);

CREATE TABLE person (
    lastname    VARCHAR2(20 CHAR),
    firstname   VARCHAR2(20 CHAR),
    idperson    INTEGER NOT NULL PRIMARY KEY,
    idaddress   INTEGER NOT NULL,
    FOREIGN KEY (idaddress) REFERENCES address(idaddress)
);

CREATE TABLE receiver (
    lastname    VARCHAR2(20 CHAR),
    firstname   VARCHAR2(20 CHAR),
    idperson    INTEGER NOT NULL PRIMARY KEY,
    idaddress   INTEGER NOT NULL,
    FOREIGN KEY (idaddress) REFERENCES address(idaddress)
);

CREATE TABLE daily_route (
    idroute         INTEGER NOT NULL PRIMARY KEY,
    Date_          DATE,
    start_address   INTEGER NOT NULL,
    end_address     INTEGER NOT NULL,
    idperson        INTEGER NOT NULL,
    FOREIGN KEY (idperson) REFERENCES delivery_drivers(idperson),
    FOREIGN KEY (start_address) REFERENCES address(idaddress),
    FOREIGN KEY (end_address) REFERENCES address(idaddress)
);

CREATE TABLE delivery (
    sending_relay           CHAR(1),
    receiving_relay         CHAR(1),
    id_sending_address      INTEGER NOT NULL,
    id_receiving_address   INTEGER NOT NULL,
    idpackage               INTEGER NOT NULL,
    sending_date            DATE,
    receiving_date          DATE,
    delivery_id             INTEGER NOT NULL PRIMARY KEY,
    idperson                INTEGER NOT NULL,
    idcustomer              INTEGER NOT NULL,
    idroute                 INTEGER NOT NULL,
    actual_address          INTEGER NOT NULL,
    FOREIGN KEY (id_sending_address) REFERENCES address(idaddress),
    FOREIGN KEY (id_receiving_address) REFERENCES address(idaddress),
    FOREIGN KEY (actual_address) REFERENCES address(idaddress),
    FOREIGN KEY (idpackage) REFERENCES package_(idpackage),
    FOREIGN KEY (idperson) REFERENCES receiver(idperson),
    FOREIGN KEY (idperson) REFERENCES customer(idcustomer),
    FOREIGN KEY (idroute) REFERENCES daily_route(idroute)
);

CREATE TABLE relay_point (
    idperson       INTEGER NOT NULL,
    idrelay        INTEGER NOT NULL PRIMARY KEY,
    company_name   VARCHAR2(20 CHAR),
    telephon       VARCHAR2(10 CHAR),
    idaddress      INTEGER NOT NULL,
    FOREIGN KEY (idaddress) REFERENCES address(idaddress),
    FOREIGN KEY (idperson) REFERENCES person(idperson)
);


CREATE TABLE department_delivery_drivers(
    number_    INTEGER NOT NULL,
    country    VARCHAR2(20 CHAR) NOT NULL,
    idperson   INTEGER NOT NULL,
    PRIMARY KEY (number_,country,idperson),
    FOREIGN KEY (idperson) REFERENCES delivery_drivers(idperson),
    FOREIGN KEY (number_,country) REFERENCES department(number_,country)
);

CREATE TABLE hours_ (
    opening_hours   VARCHAR2(20 CHAR),
    closing_hours   VARCHAR2(20 CHAR),
    day_             VARCHAR2(20 CHAR),
    start_date      DATE,
    end_date        DATE,
    idhours         INTEGER NOT NULL PRIMARY KEY,
    idrelay         INTEGER NOT NULL,
    FOREIGN KEY (idrelay) REFERENCES relay_point(idrelay)
);


CREATE TABLE relay_point_contract (
    idcontract    INTEGER NOT NULL PRIMARY KEY,
    start_date    DATE,
    notice_date   DATE,
    end_date      DATE,
    idrelay       INTEGER NOT NULL,
    FOREIGN KEY (idrelay) REFERENCES relay_point(idrelay)
);

CREATE TABLE relay_rate (
    value_         NUMBER,
    start_date    DATE,
    end_date      DATE,
    idrelayrate   INTEGER NOT NULL PRIMARY KEY,
    idcontract    INTEGER NOT NULL,
    FOREIGN KEY (idcontract) REFERENCES relay_point_contract(idcontract)
);






